const { WholeFoodsData } = require('../models');

const wholeFoodsDataSeeds = [
  {
    store: 'WholeFoods1',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods2',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods3',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods4',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods5',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods6',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods1',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods2',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods3',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods4',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods5',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods6',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods1',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods2',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods3',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods4',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods5',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods6',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'northeast',
  },
  {
    store: 'WholeFoods7',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods8',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods9',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods10',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods11',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods12',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods7',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods8',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods9',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods10',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods11',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods12',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods7',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods8',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods9',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods10',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods11',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods12',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'north atlantic',
  },
  {
    store: 'WholeFoods13',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods14',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods15',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods16',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods17',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods18',
    sku: 'Classic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods13',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods14',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods15',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods16',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods17',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods18',
    sku: 'Garlic',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods13',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods14',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods15',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods16',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods17',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
  {
    store: 'WholeFoods18',
    sku: 'Basil',
    salesWeek: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek2: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek3: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),
    salesWeek4: parseFloat((Math.random() * (10 - 1) + 1).toFixed(1)),

    sales12W: parseFloat((Math.random() * (160 - 16) + 16).toFixed(1)),
    sales52W: parseFloat((Math.random() * (520 - 52) + 52).toFixed(1)),
    price: 3.99,
    region: 'southeast',
  },
];

const seedWholeFoodsData = () => WholeFoodsData.bulkCreate(wholeFoodsDataSeeds);

module.exports = seedWholeFoodsData;
